import assert from "node:assert/strict";
import { after, test } from "node:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { db } from "../lib/server/db";
import { createSession, login, register, revokeSession, sessionUser } from "../lib/server/accounts";
import { connectedRelative, connections, requestConnection, respondConnection } from "../lib/server/family";
import { cleanActivity, cleanText, cleanUrl } from "../lib/server/clean";
import { ask } from "../lib/server/ai";
import { feedback, preferences } from "../lib/server/learning";
import { oneAccessToken, reachableConnections, saveGrant, seal, unseal } from "../lib/server/one";
const directory = mkdtempSync(join(tmpdir(), "meemaw-tests-"));
process.env.DATABASE_PATH = join(directory, "test.sqlite");
process.env.ONE_TOKEN_ENCRYPTION_KEY = "ab".repeat(32);
process.env.ONE_CLIENT_ID = "client";
process.env.ONE_CLIENT_SECRET = "secret";
process.env.ONE_REDIRECT_URI = "https://meemaw.test/api/one/callback";
const originalFetch = globalThis.fetch;
after(() => { globalThis.fetch = originalFetch; db().close(); rmSync(directory, { recursive: true, force: true }); });

test("registration, sessions, family permissions, data cleaning, cached answers and learning", async () => {
  const elder = await register({ name: "Ama", email: "ama@example.test", password: "long-password", role: "ELDER" });
  const stranger = await register({ name: "Other", email: "other@example.test", password: "long-password", role: "ELDER" });
  const relative = await register({ name: "Rex", email: "rex@example.test", password: "long-password", role: "RELATIVE", instagramUsername: "@rex" });
  const otherRelative = await register({ name: "Kojo", email: "kojo@example.test", password: "long-password", role: "RELATIVE", instagramUsername: "kojo" });
  assert.equal(relative.instagramUsername, "rex");
  assert.ok(relative.familyCode?.startsWith("MF-"));
  assert.ok(!(JSON.stringify(relative).includes("password")));
  const stored = db().prepare("SELECT password_hash FROM users WHERE id=?").get(elder.id) as { password_hash: string };
  assert.notEqual(stored.password_hash, "long-password");
  await assert.rejects(login({ email: elder.email, password: "wrong" }), /incorrect/);
  assert.equal((await login({ email: "AMA@example.test", password: "long-password" })).id, elder.id);
  await assert.rejects(register({ name: "Dup", email: elder.email, password: "long-password", role: "ELDER" }), /already exists/);
  await assert.rejects(register({ name: "Bad", email: "not-an-email", password: "long-password", role: "ELDER" }), /valid email/);
  const token = createSession(elder.id);
  assert.equal(sessionUser(token)?.id, elder.id);
  assert.equal(sessionUser("forged"), undefined);
  revokeSession(token); assert.equal(sessionUser(token), undefined);
  const expired = createSession(elder.id);
  db().prepare("UPDATE sessions SET expires_at=0").run();
  assert.equal(sessionUser(expired), undefined);
  requestConnection(elder, { familyCode: relative.familyCode, relationship: "Grandson" });
  const connection = connections(elder)[0];
  assert.equal(connection.status, "PENDING");
  assert.equal(connections(stranger).length, 0);
  assert.throws(() => connectedRelative(elder, relative.id), /approve/);
  assert.throws(() => respondConnection(otherRelative, connection.id, "ACCEPTED"), /no longer available/);
  assert.throws(() => respondConnection(elder, connection.id, "ACCEPTED"), /Only relatives/);
  respondConnection(relative, connection.id, "ACCEPTED");
  assert.equal(connectedRelative(elder, relative.id).id, relative.id);
  assert.throws(() => connectedRelative(stranger, relative.id), /approve/);
  assert.throws(() => requestConnection(elder, { familyCode: relative.familyCode, relationship: "Grandson" }), /already requested/);
  assert.equal(cleanText("<script>bad()</script> Hi&nbsp;  there\u200b"), "Hi there");
  assert.equal(cleanUrl("javascript:alert(1)"), null);
  assert.equal(cleanUrl("https://user:pass@example.test"), null);
  const clean = cleanActivity({ posts: [{ id: "1", caption: "Hello  family", publishedAt: "2026-01-01", url: "https://example.test/post?utm_source=x" }, { id: "1", caption: "duplicate" }, { caption: " ", publishedAt: "invalid" }, null], sources: [{ title: "Same", url: "https://example.test/post" }, { title: "Bad", url: "javascript:bad" }] });
  assert.equal(clean.content, "Hello family"); assert.equal(clean.sources.length, 1);
  assert.ok(clean.quality.removedItems >= 3); assert.ok(clean.quality.duplicateItems >= 2);
  delete process.env.FRIEND_API_BASE_URL;
  await assert.rejects(ask(elder, relative.id, "What’s new?"), /not connected yet/);
  process.env.FRIEND_API_BASE_URL = "https://friend.test";
  let fetches = 0; const requests: Record<string, unknown>[] = [];
  globalThis.fetch = async (url, init) => {
    if (String(url).endsWith("/activity")) { fetches++; return Response.json({ content: "Rex attended a hackathon.\nRex attended a hackathon.", sources: [{ title: "Post", url: "https://example.test/post" }] }); }
    requests.push(JSON.parse(String(init?.body)));
    return Response.json({ answer: "Rex attended a hackathon." });
  };
  const first = await ask(elder, relative.id, "What’s new?");
  assert.equal(first.quality.duplicateItems, 1);
  assert.equal(first.learning.responseStyle, "short");
  feedback(elder, first.id, "MORE_DETAIL");
  const second = await ask(elder, relative.id, "Tell me more");
  assert.equal(fetches, 1); assert.equal(second.learning.responseStyle, "detailed");
  assert.equal(requests[1].responseStyle, "detailed");
  assert.equal(preferences(stranger.id).feedbackCount, 0);
  assert.throws(() => feedback(stranger, first.id, "SHORTER"), /not found/);
  feedback(elder, second.id, "NOT_ACCURATE");
  await ask(elder, relative.id, "Please verify");
  assert.equal(fetches, 2);
  assert.equal((requests[2].feedbackGuidance as { preferVerifiedClaims: boolean }).preferVerifiedClaims, true);
  respondConnection(relative, connection.id, "DECLINED");
  await assert.rejects(ask(elder, relative.id, "Again?"), /approve/);
});

test("One encrypts per user, preserves tenant scope, rotates tokens and respects revocation", async () => {
  const relative = (db().prepare("SELECT id FROM users WHERE role='RELATIVE' LIMIT 1").get() as { id: string });
  const encrypted = seal("private token", relative.id);
  assert.ok(!encrypted.includes("private token")); assert.equal(unseal(encrypted, relative.id), "private token");
  assert.throws(() => unseal(encrypted, "different-user"));
  const token = `header.${Buffer.from(JSON.stringify({ organization_ids: ["org1"], project_ids: ["project1"] })).toString("base64url")}.signature`;
  saveGrant(relative.id, { accessToken: token, refreshToken: "old" }, Date.now() - 1);
  let rotations = 0;
  globalThis.fetch = async (url, init) => {
    if (String(url).endsWith("/oauth/token")) { rotations++; assert.ok(String(init?.body).includes("refresh_token=old")); return Response.json({ access_token: token, refresh_token: "rotated", expires_in: 604800 }); }
    const headers = init?.headers as Record<string, string>;
    assert.equal(headers["X-One-Organization-Id"], "org1"); assert.equal(headers["X-One-Project-Id"], "project1");
    return Response.json({ rows: [{ key: "connection1", platform: "instagram", name: "Rex", access: { policy: "methods", methods: ["GET"] } }] });
  };
  assert.equal(await oneAccessToken(relative.id), token);
  assert.equal(await oneAccessToken(relative.id), token); assert.equal(rotations, 1);
  assert.equal((await reachableConnections(relative.id))[0].name, "Rex");
  const grant = db().prepare("SELECT encrypted_tokens FROM one_grants WHERE user_id=?").get(relative.id) as { encrypted_tokens: string };
  assert.equal(JSON.parse(unseal(grant.encrypted_tokens, relative.id)).refreshToken, "rotated");
  globalThis.fetch = async () => new Response(null, { status: 403 });
  await assert.rejects(reachableConnections(relative.id), /does not allow/);
  assert.ok(db().prepare("SELECT user_id FROM one_grants WHERE user_id=?").get(relative.id));
  globalThis.fetch = async () => new Response(null, { status: 401 });
  await assert.rejects(reachableConnections(relative.id), /revoked/);
  assert.equal(db().prepare("SELECT user_id FROM one_grants WHERE user_id=?").get(relative.id), undefined);
});
